-- Healthcare Projects

use et2;

select * from healthcare;

-- Retrieve the names of all patients in the database.

select Name from healthcare;

-- List the unique medical conditions present in the dataset.

select distinct(Medical_Condition) from healthcare;

-- Find the total number of doctors in the healthcare system.

select count(distinct Doctor) from healthcare;

-- Retrieve the details of all female patients.

select * from healthcare where Gender='Female';

-- what is the average age of patients in the database.

select avg(age) from healthcare;

-- Identify the patients who have more than one medical condition.

select name,count(medical_condition) from healthcare group by name having count(Medical_condition)>1;

-- List the names of all doctors.

select Doctor from healthcare;

-- Identify the most common medical condition among patients.

select medical_condition,count(*) from healthcare group by medical_condition order by count(*) desc limit 1;

-- Find the patients who are older than 60 years and have diabetes.

select * from healthcare where Age>60 and Medical_condition='Diabetes';

-- Calculate the total revenue generated by the healthcare system.

select sum(Billing_Amount) as 'Total Revenue' from healthcare;

-- Find the doctor with the oldest patient.

select Name,Age,Doctor from healthcare where Age =(select max(age) from healthcare);
 
-- Calculate the average duration of medical visits.

alter table healthcare modify column duration integer;

select avg(convert(duration,signed)) from healthcare;

select avg(duration) from healthcare;

-- Give the names of patients whose name starts with A.

select Name from healthcare where Name like 'A%';

-- How many male and female patients are there in dataset.

select Gender,count(*) as 'Total' from healthcare group by Gender;

-- how many patients are normal.

select count(*) from healthcare where Test_Results ='Normal';

-- how many patients are abnormal or Inconclusive.

select count(*) from healthcare where Test_Results='Abnormal' or Test_Results='Inconclusive';

-- how many patients of blood group AB+ are there of age above 52.

select count(*) from healthcare where Blood_Type='AB+' and Age>52;

-- how many patients have paid the bill above 24890.

select count(*) from healthcare where Billing_Amount > 24890;

-- what are the names of patients having Asthma.

select Name,Medical_Condition from healthcare where Medical_Condition='Asthma';

-- how many patients have cancer.

select count(*) from healthcare where Medical_Condition='Cancer';

-- what are the names and blood groups of patients admitted to room no. 292.

select Name,Blood_Type from healthcare where Room_Number=292;

-- how many males have Arthritis.

select count(*) from healthcare where Gender='Male' and Medical_Condition='Arthritis';

-- How many patients were admitted to Harris and Sons hospital.

select count(*) from healthcare where Hospital='Harris and Sons';

-- what are the names of patients whose Insurance Provider are Cigna.

select Name,Insurance_Provider from healthcare where Insurance_Provider='Cigna';

-- Name the Medical Condition having patients whose ages is greater than average age.

select Name,Age,Medical_Condition from healthcare where age >
(select avg(age) from healthcare);












